/**
 * Synthetic OrcaSlicer-style G-code and Bambu/Orca 3MF projects for the WP5
 * import and plate-layout specs. The header lines and label formats are the
 * ones GcodeParserService and object-labels.ts read on the owner's real files
 * (e.g. "Box x 12.gcode": 12 Klipper labels, 4h03, ~112 g).
 */
import JSZip from 'jszip';

export interface GcodeOpts {
  /** per-tool grams, as `; filament used [g] = a, b, …` (omit for none) */
  toolGrams?: number[];
  /** `; total filament used [g] = …` */
  totalGrams?: number;
  minutes?: number;
  types?: string[];
  colours?: string[];
  /** Klipper instance labels (EXCLUDE_OBJECT_DEFINE) */
  labels?: string[];
  changes?: number;
}

export function gcode(o: GcodeOpts): Buffer {
  const lines: string[] = ['; generated by OrcaSlicer 2.3.0', '; HEADER_BLOCK_START'];
  if (o.minutes !== undefined) {
    const h = Math.floor(o.minutes / 60);
    const m = o.minutes % 60;
    lines.push(`; estimated printing time (normal mode) = ${h ? `${h}h ` : ''}${m}m 0s`);
  }
  lines.push('; HEADER_BLOCK_END');
  for (const l of o.labels ?? []) lines.push(`EXCLUDE_OBJECT_DEFINE NAME=${l} CENTER=100,100 POLYGON=[[0,0],[1,1]]`);
  lines.push('G28', 'G1 X10 Y10');
  for (const l of o.labels ?? []) lines.push(`EXCLUDE_OBJECT_START NAME=${l}`, 'G1 X20 E1', `EXCLUDE_OBJECT_END NAME=${l}`);
  if (o.toolGrams) lines.push(`; filament used [g] = ${o.toolGrams.map((g) => g.toFixed(2)).join(', ')}`);
  if (o.totalGrams !== undefined) lines.push(`; total filament used [g] = ${o.totalGrams.toFixed(2)}`);
  if (o.changes !== undefined) lines.push(`; total filament change = ${o.changes}`);
  if (o.colours) lines.push(`; filament_colour = ${o.colours.join(';')}`);
  if (o.types) lines.push(`; filament_type = ${o.types.join(';')}`);
  return Buffer.from(lines.join('\n') + '\n');
}

export const labels = (model: string, n: number) => Array.from({ length: n }, (_, i) => `${model}_id_${i}_copy_0`);

export interface PlateSpec {
  index: number;
  /** omit for an unsliced plate */
  seconds?: number;
  weight?: number;
  toolChanges?: number;
  gcode?: Buffer;
  png?: Buffer;
  /** slice_info `<filament>` entries (1-based id), as Bambu/Creality write them */
  filaments?: Array<{ id: number; type: string; color: string; grams: number }>;
}

export async function threeMf(plates: PlateSpec[], opts: { sliceInfo?: boolean } = {}): Promise<Buffer> {
  const zip = new JSZip();
  zip.file('3D/3dmodel.model', '<model/>');
  if (opts.sliceInfo !== false) {
    const xml = plates
      .filter((p) => p.seconds !== undefined || p.weight !== undefined || opts.sliceInfo === true)
      .map((p) => [
        '<plate>',
        `<metadata key="index" value="${p.index}"/>`,
        p.seconds !== undefined ? `<metadata key="prediction" value="${p.seconds}"/>` : '',
        p.weight !== undefined ? `<metadata key="weight" value="${p.weight}"/>` : '',
        `<metadata key="total_toolchanges" value="${p.toolChanges ?? 0}"/>`,
        ...(p.filaments ?? []).map((f) => `<filament id="${f.id}" tray_info_idx="GFA01" type="${f.type}" color="${f.color}" used_m="1" used_g="${f.grams}" />`),
        '</plate>',
      ].join(''))
      .join('');
    zip.file('Metadata/slice_info.config', `<config>${xml}</config>`);
  }
  for (const p of plates) {
    if (p.gcode) zip.file(`Metadata/plate_${p.index}.gcode`, p.gcode);
    if (p.png) zip.file(`Metadata/plate_${p.index}.png`, p.png);
  }
  return zip.generateAsync({ type: 'nodebuffer' });
}
