import { GcodeParserService } from './gcode-parser.service';

describe('GcodeParserService', () => {
  let service: GcodeParserService;

  beforeEach(() => {
    service = new GcodeParserService();
  });

  describe('parse', () => {
    it('should detect PrusaSlicer', () => {
      const gcode = '; generated by PrusaSlicer 2.7.1\n';
      const result = service.parse(gcode);
      expect(result.slicer).toContain('PrusaSlicer');
    });

    it('should detect OrcaSlicer', () => {
      const gcode = '; generated by OrcaSlicer 2.0.0\n';
      const result = service.parse(gcode);
      expect(result.slicer).toContain('OrcaSlicer');
    });

    it('should detect Cura', () => {
      const gcode = ';Generated with Cura_SteamEngine 5.6.0\n';
      const result = service.parse(gcode);
      expect(result.slicer).toContain('Cura');
    });

    it('should parse estimated print time (PrusaSlicer format)', () => {
      const gcode = '; estimated printing time (normal mode) = 2h 30m 15s\n';
      const result = service.parse(gcode);
      expect(result.estimatedTimeSeconds).toBe(2 * 3600 + 30 * 60 + 15);
    });

    it('should parse Cura TIME format', () => {
      const gcode = ';TIME:5400\n';
      const result = service.parse(gcode);
      expect(result.estimatedTimeSeconds).toBe(5400);
    });

    it('should parse total filament used in grams', () => {
      const gcode = '; total filament used [g] = 42.55\n';
      const result = service.parse(gcode);
      expect(result.filamentUsedGrams).toBeCloseTo(42.55, 1);
    });

    it('should parse filament used in mm (Cura format)', () => {
      const gcode = ';Filament used: 12345.6mm\n';
      const result = service.parse(gcode);
      // Cura stores in mm, parser converts: mm * 1000 for internal use OR keeps as mm
      expect(result.filamentUsedMm).toBeGreaterThan(0);
    });

    it('should parse layer height', () => {
      const gcode = '; layer_height = 0.20\n';
      const result = service.parse(gcode);
      expect(result.layerHeight).toBe(0.2);
    });

    it('should parse filament type', () => {
      const gcode = '; filament_type = PLA\n';
      const result = service.parse(gcode);
      expect(result.filamentType).toBe('PLA');
    });

    it('should parse nozzle temperature', () => {
      const gcode = '; nozzle_temperature = 215\n';
      const result = service.parse(gcode);
      expect(result.nozzleTemp).toBe(215);
    });

    it('should parse bed temperature', () => {
      const gcode = '; bed_temperature = 60\n';
      const result = service.parse(gcode);
      expect(result.bedTemp).toBe(60);
    });

    it('should parse filament colors', () => {
      const gcode = '; filament_colour = #FF0000;#00FF00;#0000FF\n';
      const result = service.parse(gcode);
      expect(result.filamentColors).toEqual(['#FF0000', '#00FF00', '#0000FF']);
    });

    it('should count tool change commands', () => {
      const gcode = [
        '; some comment',
        'T0',
        'G1 X10 Y10',
        'T1',
        'G1 X20 Y20',
        'T0',
        'G1 X30 Y30',
        'T1',
      ].join('\n');
      const result = service.parse(gcode);
      expect(result.totalFilamentChanges).toBeGreaterThan(0);
    });

    it('should parse multi-tool filament grams (comma-separated)', () => {
      const gcode = '; filament used [g] = 49.83, 15.77, 50.62, 36.57\n';
      const result = service.parse(gcode);
      expect(result.tools.length).toBe(4);
      expect(result.tools[0].filamentGrams).toBeCloseTo(49.83, 1);
      expect(result.tools[1].filamentGrams).toBeCloseTo(15.77, 1);
      expect(result.tools[2].filamentGrams).toBeCloseTo(50.62, 1);
      expect(result.tools[3].filamentGrams).toBeCloseTo(36.57, 1);
    });

    it('should assign color hex to tools from filament_colour', () => {
      const gcode = [
        '; filament_colour = #000000;#FF0000;#FFFF80;#FFBDC4',
        '; filament used [g] = 49.83, 15.77, 50.62, 36.57',
        '; filament_type = PLA;PLA;PLA;PLA',
      ].join('\n');
      const result = service.parse(gcode);
      expect(result.tools[0].colorHex).toBe('#000000');
      expect(result.tools[1].colorHex).toBe('#FF0000');
      expect(result.tools[2].colorHex).toBe('#FFFF80');
      expect(result.tools[3].colorHex).toBe('#FFBDC4');
    });

    it('should handle single-tool gcode', () => {
      const gcode = [
        '; generated by PrusaSlicer',
        '; total filament used [g] = 25.50',
        '; estimated printing time = 1h 15m',
        '; filament_type = PETG',
      ].join('\n');
      const result = service.parse(gcode);
      expect(result.filamentUsedGrams).toBeCloseTo(25.5, 1);
      expect(result.filamentType).toBe('PETG');
      expect(result.tools.length).toBeLessThanOrEqual(1);
    });

    it('should handle Buffer input', () => {
      const gcode = Buffer.from('; total filament used [g] = 10.5\n');
      const result = service.parse(gcode);
      expect(result.filamentUsedGrams).toBeCloseTo(10.5, 1);
    });

    it('should handle empty input', () => {
      const result = service.parse('');
      expect(result.slicer).toBeNull();
      expect(result.filamentUsedGrams).toBeNull();
      expect(result.tools).toEqual([]);
    });
  });

  describe('parseHeader', () => {
    it('should parse header for large files without reading entire file', () => {
      // parseHeader reads first/last N lines
      const gcode = Buffer.from('; filament_type = PLA\n; filament used [g] = 5.0\nG1 X0 Y0\n');
      const result = service.parseHeader(gcode);
      expect(result.filamentType).toBe('PLA');
    });
  });
});
