import { GcodeParserService } from './gcode-parser.service';
import { matchPrinter, noMatchingPrinter } from './printer-match';
import { cleanProfileName, detectPrinterModel, printerModelFromProjectSettings } from './printer-model';

// Excerpts of the owner's real files (Documents/3D printing), header and config-block lines kept verbatim.
const ORCA_CREALITY_HI = [
  '; generated by OrcaSlicer 2.4.2 on 2026-09-11 at 20:13:21',
  '; filament_settings_id = "eSUN PLA+ @System";"eSUN PLA+ @System";"eSUN PLA+ @System"',
  '; default_print_profile = 0.20mm Standard @Creality Hi',
  '; print_settings_id = 0.20mm Standard @Creality Hi',
  '; printer_model = Creality Hi',
  '; printer_notes = ',
  '; printer_settings_id = Creality Hi 0.4 nozzle',
  '; printer_structure = i3',
  '; printer_technology = FFF',
  '; printer_variant = 0.4',
].join('\n');

const ORCA_ENDER3V3_COPY = [
  '; generated by OrcaSlicer 2.4.2',
  '; printer_model = Creality Ender-3 V3',
  '; printer_settings_id = Creality Ender-3 V3 0.4 nozzle - Copy',
].join('\n');

const PRUSA_MK3S = [
  '; generated by PrusaSlicer 2.4.2+win64 on 2022-08-30 at 09:46:55 UTC',
  '; printer_model = MK3S',
  "; printer_notes = Don't remove the following keywords! These keywords are used in the \"compatible printer\" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\\nPRINTER_VENDOR_PRUSA3D\\nPRINTER_MODEL_MK3\\n",
  '; printer_settings_id = Original Prusa i3 MK3S & MK3S+',
].join('\n');

const CREALITY_PRINT_4 = [
  ';FLAVOR:Creality OS',
  ';TIME:1033.45',
  ';Filament Weight:3.961325',
  ';Creality Print GCode Generated by CXEngine',
  ';Creality Print Version : V4.3.8.6984',
  ';----------Machine Config--------------',
  ';Machine Name:F001',
  ';Machine Height:250',
].join('\n');

describe('detectPrinterModel (real slicer headers)', () => {
  it('reads printer_model from an OrcaSlicer config block', () => {
    expect(detectPrinterModel(ORCA_CREALITY_HI)).toBe('Creality Hi');
    expect(detectPrinterModel(ORCA_ENDER3V3_COPY)).toBe('Creality Ender-3 V3');
  });

  it('reads PrusaSlicer printer_model (MK3S), not the notes', () => {
    expect(detectPrinterModel(PRUSA_MK3S)).toBe('MK3S');
  });

  it('falls back to the printer profile name without its nozzle and copy tails', () => {
    expect(detectPrinterModel('; printer_settings_id = Creality Hi 0.4 nozzle')).toBe('Creality Hi');
    expect(detectPrinterModel('; printer_settings_id = "Bambu Lab X1 Carbon 0.4 nozzle"')).toBe('Bambu Lab X1 Carbon');
    expect(detectPrinterModel('; printer_settings_id = Creality Ender-3 V3 0.4 nozzle - Copy')).toBe('Creality Ender-3 V3');
  });

  it('maps the Creality Print 4 machine code F001 to the Ender-3 V3', () => {
    expect(detectPrinterModel(CREALITY_PRINT_4)).toBe('Creality Ender-3 V3');
    expect(detectPrinterModel(';Machine Name:K1C')).toBe('K1C');
  });

  it("reads Cura's target machine and PrusaSlicer's PRINTER_MODEL_ note as last resorts", () => {
    expect(detectPrinterModel(';TARGET_MACHINE.NAME:Creality Ender-3 Pro')).toBe('Creality Ender-3 Pro');
    expect(detectPrinterModel('; printer_notes = PRINTER_VENDOR_PRUSA3D\\nPRINTER_MODEL_MK4\\n')).toBe('MK4');
  });

  it('returns null when the file names no printer (or a blank printer_model)', () => {
    expect(detectPrinterModel('; generated by OrcaSlicer 2.3.0\nG28\n')).toBeNull();
    expect(detectPrinterModel('; printer_model = \n; printer_notes = \n')).toBeNull();
    expect(detectPrinterModel('G1 X10 ; printer_model = Not a comment line')).toBeNull();
  });

  it('cleanProfileName strips "@vendor" and "(project)" parts', () => {
    expect(cleanProfileName('Creality Hi 0.4 nozzle(Anas.3mf)')).toBe('Creality Hi');
    expect(cleanProfileName('Bambu Lab P1S 0.4 nozzle @BBL')).toBe('Bambu Lab P1S');
  });

  it('GcodeParserService.parse and parseHeader carry printerModel (config block in the tail of a big file)', () => {
    const parser = new GcodeParserService();
    expect(parser.parse(ORCA_CREALITY_HI).printerModel).toBe('Creality Hi');
    const big = Buffer.from(['; generated by OrcaSlicer 2.4.2', 'G1 X1'.repeat(1).padEnd(200_000, ' '), ORCA_CREALITY_HI].join('\n'));
    expect(parser.parseHeader(big).printerModel).toBe('Creality Hi');
  });
});

describe('printerModelFromProjectSettings (3MF)', () => {
  it('reads printer_model, else the cleaned printer_settings_id', () => {
    expect(printerModelFromProjectSettings(JSON.stringify({ printer_model: 'Creality Hi', printer_settings_id: 'Creality Hi' }))).toBe('Creality Hi');
    expect(printerModelFromProjectSettings(JSON.stringify({ printer_model: '', printer_settings_id: 'Bambu Lab A1 0.4 nozzle' }))).toBe('Bambu Lab A1');
    expect(printerModelFromProjectSettings('not json')).toBeNull();
    expect(printerModelFromProjectSettings(JSON.stringify({}))).toBeNull();
  });
});

describe('matchPrinter', () => {
  const printers = [
    { id: 'p-hi', name: 'HI', model: null, isActive: true },
    { id: 'p-e3', name: 'Ender 3 V3 #1', model: 'Ender-3 V3', isActive: true },
    { id: 'p-e', name: 'Ender', model: null, isActive: true },
    { id: 'p-mk3', name: 'Prusa MK3S', model: null, isActive: true },
    { id: 'p-old', name: 'Bambu Lab X1 Carbon', model: 'Bambu Lab X1 Carbon', isActive: false },
  ];

  it('matches by words, case and punctuation ignored', () => {
    expect(matchPrinter('Creality Hi', printers)?.id).toBe('p-hi');
    expect(matchPrinter('MK3S', printers)?.id).toBe('p-mk3');
  });

  it('prefers the most specific printer (model field "Ender-3 V3" over a printer named "Ender")', () => {
    expect(matchPrinter('Creality Ender-3 V3', printers)?.id).toBe('p-e3');
  });

  it('matches a name written without spaces', () => {
    expect(matchPrinter('Creality Ender3V3', [{ id: 'x', name: 'Ender-3 V3', model: null }])?.id).toBe('x');
  });

  it('never matches an inactive printer, and returns null when nothing matches', () => {
    expect(matchPrinter('Bambu Lab X1 Carbon', printers)).toBeNull();
    expect(matchPrinter('Creality K1 Max', printers)).toBeNull();
    expect(matchPrinter(null, printers)).toBeNull();
    expect(matchPrinter('   ', printers)).toBeNull();
  });

  it('an exact match wins over a partial one', () => {
    const list = [{ id: 'a', name: 'Creality Hi Combo', model: null }, { id: 'b', name: 'creality-hi', model: null }];
    expect(matchPrinter('Creality Hi', list)?.id).toBe('b');
  });

  it('says what the file was sliced for when nothing matches', () => {
    expect(noMatchingPrinter('Creality K1 Max')).toBe('Sliced for Creality K1 Max — no matching printer');
  });
});
