/**
 * Files the e2e script uploads, built in memory (ported from
 * src/common/utils/__fixtures__/test-images.ts and
 * src/products/__fixtures__/slicer-files.ts), and a PDF text reader.
 */
import zlib from 'node:zlib';

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(buf) {
  let c = 0xffffffff;
  for (const b of buf) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function pngChunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const td = Buffer.concat([Buffer.from(type, 'latin1'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(td), 0);
  return Buffer.concat([len, td, crc]);
}

/** A real, decodable 2×2 RGBA PNG. */
export function makePng() {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(2, 0);
  ihdr.writeUInt32BE(2, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  const raw = Buffer.from([0, 255, 0, 0, 255, 0, 255, 0, 255, 0, 0, 0, 255, 255, 255, 255, 255, 255]);
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', zlib.deflateSync(raw)),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

function seg(marker, payload) {
  const head = Buffer.alloc(4);
  head[0] = 0xff;
  head[1] = marker;
  head.writeUInt16BE(payload.length + 2, 2);
  return Buffer.concat([head, payload]);
}

export const GPS_SECRET = 'GPSSECRET-23.58N-58.40E';

/** Little-endian TIFF: IFD0 = [GPS IFD pointer], GPS IFD holding the ASCII secret. */
function exifTiff() {
  const secret = Buffer.from(`${GPS_SECRET}\0`, 'latin1');
  const ifd0Size = 2 + 12 + 4;
  const gpsIfdOffset = 8 + ifd0Size;
  const secretOffset = gpsIfdOffset + 2 + 12 + 4;
  const t = Buffer.alloc(secretOffset + secret.length);
  t.write('II', 0, 'latin1');
  t.writeUInt16LE(42, 2);
  t.writeUInt32LE(8, 4);
  t.writeUInt16LE(1, 8);
  t.writeUInt16LE(0x8825, 10);
  t.writeUInt16LE(4, 12);
  t.writeUInt32LE(1, 14);
  t.writeUInt32LE(gpsIfdOffset, 18);
  t.writeUInt32LE(0, 22);
  t.writeUInt16LE(1, gpsIfdOffset);
  t.writeUInt16LE(0x001b, gpsIfdOffset + 2);
  t.writeUInt16LE(7, gpsIfdOffset + 4);
  t.writeUInt32LE(secret.length, gpsIfdOffset + 6);
  t.writeUInt32LE(secretOffset, gpsIfdOffset + 10);
  t.writeUInt32LE(0, gpsIfdOffset + 14);
  secret.copy(t, secretOffset);
  return t;
}

/** Structurally valid JPEG (SOF0 16×16) with an Exif APP1 carrying a GPS IFD. */
export function makeGpsJpeg() {
  const sof = Buffer.alloc(15);
  sof[0] = 8;
  sof.writeUInt16BE(16, 1);
  sof.writeUInt16BE(16, 3);
  sof[5] = 3;
  return Buffer.concat([
    Buffer.from([0xff, 0xd8]),
    seg(0xe0, Buffer.from('JFIF\0\x01\x01\0\0\x01\0\x01\0\0', 'latin1')),
    seg(0xe1, Buffer.concat([Buffer.from('Exif\0\0', 'latin1'), exifTiff()])),
    seg(0xdb, Buffer.alloc(65, 1)),
    seg(0xc0, sof),
    seg(0xda, Buffer.from([1, 1, 0, 0, 0x3f, 0, 0, 0, 0, 0])),
    Buffer.from([0x12, 0x34, 0x56, 0x78, 0x9a]),
    Buffer.from([0xff, 0xd9]),
  ]);
}

export const SVG_AS_PNG = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>');

/** OrcaSlicer-style single-tool G-code the importer accepts (slicer-files.ts `gcode`). */
export function makeGcode({ grams = 5, minutes = 20, type = 'PLA', colour = '#000000' } = {}) {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return Buffer.from([
    '; generated by OrcaSlicer 2.3.0',
    '; HEADER_BLOCK_START',
    `; estimated printing time (normal mode) = ${h ? `${h}h ` : ''}${m}m 0s`,
    '; HEADER_BLOCK_END',
    'G28',
    'G1 X10 Y10',
    `; filament used [g] = ${grams.toFixed(2)}`,
    `; total filament used [g] = ${grams.toFixed(2)}`,
    `; filament_colour = ${colour}`,
    `; filament_type = ${type}`,
    '',
  ].join('\n'));
}

/**
 * Text drawn by a PDFKit document with the standard fonts: inflates every
 * FlateDecode stream and decodes the hex/literal strings of TJ/Tj operators as
 * WinAnsi. Good enough to find a label; wrapping splits a label across lines,
 * so compare with `pdfContains` (whitespace-insensitive).
 */
export function pdfText(buf) {
  const s = buf.toString('latin1');
  const dec = { decode: winAnsi };
  const out = [];
  const re = /stream\r?\n/g;
  let m;
  while ((m = re.exec(s))) {
    const start = m.index + m[0].length;
    const end = s.indexOf('endstream', start);
    if (end < 0) break;
    const dict = s.slice(Math.max(0, m.index - 300), m.index);
    let content = buf.subarray(start, end);
    if (/\/FlateDecode/.test(dict.slice(dict.lastIndexOf('<<')))) {
      try { content = zlib.inflateSync(content); } catch { try { content = zlib.inflateSync(content.subarray(0, content.length - 1)); } catch { continue; } }
    }
    const text = content.toString('latin1');
    for (const t of text.matchAll(/\[(.*?)\]\s*TJ|<([0-9a-fA-F]*)>\s*Tj|\(((?:\\.|[^\\)])*)\)\s*Tj/gs)) {
      if (t[1] !== undefined) {
        for (const p of t[1].matchAll(/<([0-9a-fA-F]*)>|\(((?:\\.|[^\\)])*)\)/g)) {
          out.push(p[1] !== undefined ? dec.decode(Buffer.from(p[1], 'hex')) : unescapeLiteral(p[2], dec));
        }
      } else if (t[2] !== undefined) out.push(dec.decode(Buffer.from(t[2], 'hex')));
      else out.push(unescapeLiteral(t[3], dec));
    }
    re.lastIndex = end;
  }
  return out.join('');
}

/** Windows-1252 (PDF WinAnsiEncoding). Node's TextDecoder('windows-1252') decodes as Latin-1. */
const CP1252 = '€�‚ƒ„…†‡ˆ‰Š‹Œ�Ž��‘’“”•–—˜™š›œ�žŸ';
function winAnsi(bytes) {
  let s = '';
  for (const b of bytes) s += b >= 0x80 && b <= 0x9f ? CP1252[b - 0x80] : String.fromCharCode(b);
  return s;
}

function unescapeLiteral(lit, dec) {
  const bytes = [];
  for (let i = 0; i < lit.length; i++) {
    const c = lit[i];
    if (c !== '\\') { bytes.push(c.charCodeAt(0) & 0xff); continue; }
    const n = lit[++i];
    const map = { n: 10, r: 13, t: 9, b: 8, f: 12, '(': 40, ')': 41, '\\': 92 };
    if (n in map) bytes.push(map[n]);
    else if (/[0-7]/.test(n)) {
      let oct = n;
      while (oct.length < 3 && /[0-7]/.test(lit[i + 1] ?? '')) oct += lit[++i];
      bytes.push(parseInt(oct, 8) & 0xff);
    }
  }
  return dec.decode(Buffer.from(bytes));
}

export const pdfContains = (buf, needle) => pdfText(buf).replace(/\s+/g, '').includes(String(needle).replace(/\s+/g, ''));
